version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
      timezone: 'America/Chicago'
    open-pull-requests-limit: 3
    ignore:
      # ignore all patch updates
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

      # @date-io/luxon@1 requires luxon@1
      - dependency-name: 'luxon'
      # luxon@1 requires @types/luxon@1
      - dependency-name: '@types/luxon'
