version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '11:00'
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '@date-io/luxon'
        versions:
          - '<=3.0.0'
      - dependency-name: '@date-io/core'
        versions:
          - 2.10.7
