platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/oci-build-task }

params:
  CONTEXT: goalert
  DOCKERFILE: goalert/devtools/ci/dockerfiles/goalert/Dockerfile.buildx

inputs:
  - name: goalert

outputs:
  - name: image

run: { path: build }
