platform: linux

image_resource:
  type: registry-image
  source: { repository: vito/oci-build-task }

params:
  CONTEXT: .
  DOCKERFILE: goalert/devtools/ci/dockerfiles/goalert/Dockerfile

inputs:
  - name: goalert
  - name: bin

outputs:
  - name: image

run: { path: build }
