platform: linux
caches:
  - path: /go/pkg
  - path: /root/go/pkg
  - path: goalert/web/src/node_modules
  - path: /usr/local/share/.cache/yarn/v4
  - path: /root/.cache
inputs:
  - name: goalert
outputs:
  - name: bin
    path: goalert/bin
  - name: db-dumps
    path: goalert/smoketest/smoketest_db_dump
  - name: videos
    path: goalert/web/src/cypress/videos
  - name: screenshots
    path: goalert/web/src/cypress/screenshots
image_resource:
  type: registry-image
  source:
    repository: gcr.io/tgt-goalert/goalert-build-env
    username: _json_key
    password: ((storage-account))
run:
  dir: goalert
  path: ./devtools/ci/tasks/scripts/build-test.sh
