blank_issues_enabled: false
contact_links:
  - name: Chat for questions and support
    url: https://gophers.slack.com/archives/CJQGZPYLV
    about: "This issue tracker is not for support questions. Visit the gophers community Slack and the #goalert channel for assistance!"
