version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/web/src/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "@date-io/luxon"
          version_requirement: "<=2.0.1"
