version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/web/src/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "@date-io/luxon"
          version_requirement: "<=2.4.0"
      - match:
        dependency_name: "@material-ui/core"
        version_requirement: "<=4.9.x"
