name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1.8.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '15'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '250'
          l_label: 'size/l'
          l_max_size: '500'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 500 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          files_to_ignore: 'yarn.lock graphql2/generated.go graphql2/maplimit.go graphql2/mapconfig.go pkg/sysapi/sysapi_grpc.pb.go pkg/sysapi/sysapi.pb.go swo/swodb/db.go swo/swodb/models.go swo/swodb/queries.sql.go web/src/schema.d.ts expflag.d.ts Makefile.binaries.mk gadb/db.go gadb/models.go gadb/queries.sql.go migrate/schema.sql'
